version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: rafaelrocha007/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8081:80
    depends_on:
      - app
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["sh","-c", "npm install -y && node index.js"]
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
